Repository open-AIMS/rrap-dg, pull requests merged in 2024-07, with the labels that each got.

#7 Update README table of contents
  README.md
  rrap_dg/juliapkg.json
Labels: documentation

#8 Allow use with rrapdg data package or RM/RME datasets
  README.md
  rrap_dg/Manifest.toml
  rrap_dg/Project.toml
  rrap_dg/initial_coral_cover/icc.jl
Labels: enhancement

#11 Clean up M&DS data store interface
  README.md
  rrap_dg/data_store/__init__.py
  rrap_dg/data_store/data_store.py
  rrap_dg/main.py
Labels: maintenance

#12 Initial data package templating
  README.md
  rrap_dg/dpkg_template/__init__.py
  rrap_dg/dpkg_template/dpkg_template.py
  rrap_dg/main.py
Labels: enhancement

#13 Support creating multiple initial coral covers with user-specifiable bin sizes
  README.md
  rrap_dg/initial_coral_cover/icc.jl
  rrap_dg/initial_coral_cover/initial_coral_cover.py
  rrap_dg/juliapkg.json
Labels: enhancement
